---
- name: Test
  hosts: all
  become: true
  gather_facts: false

  vars:
    dist: "/home"
    target: "/doly"
  tasks:
    - name: test
      ansible.builtin.command:
        cmd: echo $USER
      register: command_result
    - name: print
      debug:
        var: command_result.stdout
    - name: test2
      command:
        cmd: lscpu
      register: command_result
    - name: print result
      debug:
        var: command_result.stdout
    - name: variable combine test
      command:
        cmd: ls {{ dist }}{{ target }}
      register: command_result
    - name: print result
      debug:
        var: command_result.stdout
