---
- name: Qemu-img Creation
  hosts: all
  become: true
  gather_facts: true

  vars:
    - disk_size: 32G
    - disk_names:
        - { name: test01 }
        - { name: test02 }
    - disk_location: /var/lib/libvirt/boot/
    - format: qcow2

  tasks:
    - name: Create New Virtual Disk
      command: >
        qemu-img create -f {{ format }} - b
