---
- name: apt Update Upgrade
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: apt update
      apt:
        update_cache: true
    - name: apt upgrade
      apt:
        upgrade: true
