---
- name: Warning Netplan configuration
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Netplan Configuration must be required before configuring iptables
      command:
        cmd: cat /etc/netplan/50-cloud-init.yaml
      register: command_result
    - name: print result
      debug:
        var: command_result.stdout

- name: Network configuration
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Configure iptables
      command:
        cmd: iptables -P FORWARD ACCEPT

    - name: Destroying default
      command:
        cmd: virsh net-destroy default
      register: command_result
      ignore_errors: true
    - name: Print result
      debug:
        var: command_result.stdout

    - name: Undefining default
      command:
        cmd: virsh net-undefine default
      register: command_result
      ignore_errors: true
    - name: Print result
      debug:
        var: command_result.stdout

- name: virsh network configuration
  hosts: all
  gather_facts: false

  tasks:
    - name: Print User name
      command:
        cmd: echo $USER
      register: command_result
    - name: Print result
      debug:
        var: command_result.stdout

    - name: Copy bridge-conf.xml
      copy:
        src: ~/pro/ansible/bridge_conf/kvmbr0.xml
        dest: ~/vm-config

    - name: Configure yourself
      debug:
        msg:
          - "virsh net-define ~/vm-config/kvmbr0.xml"
          - "virsh net-start default"
          - "virsh net-autostart default"
